const NAME_OR_PASSWORD_IS_REQUIRED = 'NAME_OR_PASSWORD_IS_REQUIRED';
const NAME_ALRADY_EXIST = 'NAME_ALRADY_EXIST';
const USER_NOT_EXIST = 'USER_NOT_EXIST';
const PASSWORD_ERROR = 'PASSWORD_ERROR';
const UNAUTHORIZATION = 'UNAUTHORIZATION';
const NO_PERMISSION = 'NO_PERMISSION';

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  NAME_ALRADY_EXIST,
  USER_NOT_EXIST,
  PASSWORD_ERROR,
  UNAUTHORIZATION,
  NO_PERMISSION,
};